// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQBJW6YDvOuDHAwXrPG4KPcaCLuB1aodg',
    appId: '1:1025005736352:web:f8e13fa142c026662954c5',
    messagingSenderId: '1025005736352',
    projectId: 'barber-35eca',
    authDomain: 'barber-35eca.firebaseapp.com',
    storageBucket: 'barber-35eca.firebasestorage.app',
    measurementId: 'G-0PBR297PF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VeZDlLuye1_qadD-GFcEzrsGqXliPgc',
    appId: '1:1025005736352:android:4302f12914eaac3d2954c5',
    messagingSenderId: '1025005736352',
    projectId: 'barber-35eca',
    storageBucket: 'barber-35eca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1AxH44vTSo2bNA-NbzWHhsrhsC1R5KHk',
    appId: '1:1025005736352:ios:14705865c54eed022954c5',
    messagingSenderId: '1025005736352',
    projectId: 'barber-35eca',
    storageBucket: 'barber-35eca.firebasestorage.app',
    iosBundleId: 'com.artdeco.barberShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1AxH44vTSo2bNA-NbzWHhsrhsC1R5KHk',
    appId: '1:1025005736352:ios:14705865c54eed022954c5',
    messagingSenderId: '1025005736352',
    projectId: 'barber-35eca',
    storageBucket: 'barber-35eca.firebasestorage.app',
    iosBundleId: 'com.artdeco.barberShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQBJW6YDvOuDHAwXrPG4KPcaCLuB1aodg',
    appId: '1:1025005736352:web:0e7e0b6fdf252b552954c5',
    messagingSenderId: '1025005736352',
    projectId: 'barber-35eca',
    authDomain: 'barber-35eca.firebaseapp.com',
    storageBucket: 'barber-35eca.firebasestorage.app',
    measurementId: 'G-71DS7KDEZ4',
  );
}
